spring.application.name=HomeServerAPI
#spring.datasource.url=jdbc:postgresql://postgres-db:5432/postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public
#logging.level.org.springframework=DEBUG
